branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.9.1\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - git clone https://github.com/jlaine/qdjango.git
  - cd qdjango
  - qmake qdjango.pro
  - mingw32-make
  - mingw32-make install
  - cd ..
build_script:
  - qmake woke-qt.pro
  - mingw32-make
after_build:
  - windeployqt release/woke.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - cmd: cp C:/Qt/5.9.1/mingw53_32/lib/libqdjango-db0.a C:/projects/woke"
  - cmd: cp C:/Qt/5.9.1/mingw53_32/lib/qdjango-db0.dll C:/projects/woke"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\woke*.exe
  - path: release
    type: zip
