branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.9.1\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake woke-qt.pro
  - mingw32-make
after_build:
  - windeployqt release/woke.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\woke*.exe
  - path: release
    type: zip
