language: cpp

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update
  
install:
  - sudo apt-get install python3.5 --allow-unauthenticated
  - sudo apt-get install python3.5-dev --allow-unauthenticated
  - sudo apt-get install qt59base
  - source /opt/qt59/bin/qt59-env.sh
  - git clone https://github.com/tmstieff/qdjango.git
  - cd qdjango
  - qmake
  - make
  - sudo make install
  - cd ../
  - git clone https://github.com/pybind/pybind11.git
  - cd pybind11
  - mkdir build
  - cd build
  - python --version
  - python3 --version
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 10
  - python3 -m pip install pytest
  - cmake ..
  - sudo make install
  - sudo ldconfig
  - cd ../../
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
  - qmake -v
  - qmake CONFIG+=test
  - make
  - ./woke-test
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - sed -i -e 's|^Icon=.*|Icon=woke|g' ./appdir/usr/share/applications/*.desktop ; mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; touch appdir/usr/share/icons/hicolor/256x256/apps/woke.png # Workaround for https://github.com/tmstieff/Woke/issues/2#issuecomment-343653712
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file ./APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./Woke*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
