language: C++
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-get update
install:
  - sudo apt-get install qt59base
  - git clone git@github.com:jlaine/qdjango.git
  - cd qdjango
  - qmake
  - make
  - sudo make install
script:
  - source /opt/qt59/bin/qt59-env.sh
  - qmake -v
  - qmake CONFIG+=test
  - make
  - qmake
  - make

