language: cpp
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get update
install:
  - sudo apt-get install qt59base
  - source /opt/qt59/bin/qt59-env.sh
  - git clone https://github.com/jlaine/qdjango.git
  - cd qdjango
  - qmake
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - qmake -v
  - qmake CONFIG+=test
  - make
  - ./woke-test
  - qmake
  - make

